document.addEventListener("DOMContentLoaded",()=>{const STORE={lat:-23.5884432,lon:-46.6377658},KEY="yuba-area-overrides-v1";const $=id=>document.getElementById(id),u={endereco:$("endereco"),gps:$("gps"),buscar:$("buscar"),rota:$("rota"),status:$("status"),resultado:$("resultado"),situacao:$("situacao"),titulo:$("titulo-resultado"),icone:$("icone-resultado"),frete:$("frete"),regiao:$("regiao"),distancia:$("distancia"),tempo:$("tempo"),observacao:$("observacao")};let areas=[],atual=null;
const overrides=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}};
async function iniciar(){try{const r=await fetch("./dados/delivery_regions.geojson?v=5");if(!r.ok)throw Error();const g=await r.json(),o=overrides();areas=g.features.filter(f=>f.geometry?.type==="Polygon").map(f=>({...f,properties:{...f.properties,...(o[f.properties.id]||{})},area:polyArea(f.geometry.coordinates[0])}));u.status.textContent=`${areas.length} áreas carregadas.`}catch(e){u.status.textContent="Erro ao carregar as áreas.";console.error(e)}}iniciar();
async function geo(q){const p=new URLSearchParams({q,format:"jsonv2",limit:"1",countrycodes:"br",addressdetails:"1","accept-language":"pt-BR"}),r=await fetch(`https://nominatim.openstreetmap.org/search?${p}`,{headers:{Accept:"application/json"}});if(!r.ok)throw Error("Falha na consulta.");const d=await r.json();if(!d.length)throw Error("Endereço não encontrado. Inclua número, cidade e estado.");return{lat:+d[0].lat,lon:+d[0].lon,endereco:d[0].display_name}}
async function rev(lat,lon){const p=new URLSearchParams({lat,lon,format:"jsonv2","accept-language":"pt-BR"}),r=await fetch(`https://nominatim.openstreetmap.org/reverse?${p}`,{headers:{Accept:"application/json"}});if(!r.ok)return`${lat.toFixed(6)}, ${lon.toFixed(6)}`;const d=await r.json();return d.display_name||`${lat.toFixed(6)}, ${lon.toFixed(6)}`}
function inRing(x,y,a){let c=false;for(let i=0,j=a.length-1;i<a.length;j=i++){const[xi,yi]=a[i],[xj,yj]=a[j];if((yi>y)!=(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)c=!c}return c}
function inPoly(x,y,r){if(!r.length||!inRing(x,y,r[0]))return false;for(let i=1;i<r.length;i++)if(inRing(x,y,r[i]))return false;return true}
function polyArea(a){let s=0;for(let i=0,j=a.length-1;i<a.length;j=i++)s+=a[j][0]*a[i][1]-a[i][0]*a[j][1];return Math.abs(s/2)}
function achar(lat,lon){const es=areas.filter(f=>f.properties.active!==false&&inPoly(lon,lat,f.geometry.coordinates)),risco=es.find(f=>f.properties.risk);if(risco)return risco;return es.filter(f=>f.properties.service&&Number.isFinite(+f.properties.price)).sort((a,b)=>a.area-b.area)[0]||null}
function km(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,D1=rad(c-a),D2=rad(d-b),q=Math.sin(D1/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(D2/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
function show(f,lat,lon){atual={lat,lon};const d=km(STORE.lat,STORE.lon,lat,lon);u.resultado.classList.remove("oculto","erro");if(!f){u.resultado.classList.add("erro");u.situacao.textContent="Fora da cobertura";u.titulo.textContent="Endereço não atendido";u.icone.textContent="!";u.frete.textContent="Indisponível";u.regiao.textContent="Fora das áreas cadastradas";u.distancia.textContent=`${d.toFixed(1).replace(".",",")} km`;u.tempo.textContent="Consulte a Produtos Yuba";u.observacao.textContent="Este endereço não está em nenhuma área cadastrada.";return}if(f.properties.risk){u.resultado.classList.add("erro");u.situacao.textContent="Área de risco";u.titulo.textContent="Entrega indisponível";u.icone.textContent="!";u.frete.textContent="Não atendemos";u.regiao.textContent=f.properties.label||f.properties.name;u.distancia.textContent=`${d.toFixed(1).replace(".",",")} km`;u.tempo.textContent="Não aplicável";u.observacao.textContent=f.properties.description||"Área marcada como não atendida.";return}u.situacao.textContent="Entrega disponível";u.titulo.textContent="Endereço dentro da cobertura";u.icone.textContent="✓";u.frete.textContent=money(+f.properties.price);u.regiao.textContent=f.properties.label||f.properties.name;u.distancia.textContent=`${d.toFixed(1).replace(".",",")} km`;u.tempo.textContent=`aprox. ${Math.max(20,Math.round(d/22*60+15))} min`;u.observacao.textContent="Distância em linha reta e tempo aproximado; o trajeto real pode variar."}
function load(on,msg=""){u.buscar.disabled=on;u.gps.disabled=on;u.buscar.textContent=on?"Aguarde...":"🚚 Calcular frete";u.status.textContent=msg}
u.buscar.onclick=async()=>{const q=u.endereco.value.trim();if(!q){u.status.textContent="Digite um endereço completo.";return u.endereco.focus()}load(true,"Localizando endereço...");try{const l=await geo(q);u.endereco.value=l.endereco;show(achar(l.lat,l.lon),l.lat,l.lon);u.status.textContent="Consulta concluída."}catch(e){u.status.textContent=e.message}finally{load(false,u.status.textContent)}};
u.endereco.onkeydown=e=>{if(e.key==="Enter")u.buscar.click()};
u.gps.onclick=()=>{if(!navigator.geolocation)return u.status.textContent="Geolocalização indisponível.";load(true,"Obtendo sua localização...");navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;try{u.endereco.value=await rev(lat,lon);show(achar(lat,lon),lat,lon);u.status.textContent="Localização consultada."}finally{load(false,u.status.textContent)}},e=>load(false,({1:"Permissão negada.",2:"Localização indisponível.",3:"Tempo esgotado."})[e.code]||"Falha na localização."),{enableHighAccuracy:true,timeout:15000,maximumAge:60000})};
u.rota.onclick=()=>{if(!atual)return;window.open(`https://www.google.com/maps/dir/?api=1&origin=${STORE.lat},${STORE.lon}&destination=${atual.lat},${atual.lon}`,"_blank","noopener,noreferrer")};
});
